services:
  # Development services
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: recall_butler
      POSTGRES_PASSWORD: "bTzxb2q9Mwhqp_Ttlmc2IWOZuh5veP90"
    volumes:
      - recall_butler_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "MDvqunMSmAn_t4IkCsovoAvC8NU8VqjP"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: pgvector/pgvector:pg16
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: recall_butler_test
      POSTGRES_PASSWORD: "_9yIIV1wHaCCe_cpX896akxRhVx7UZHn"
    volumes:
      - recall_butler_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "yCJ4jabseqxTEnITVg1rPR22YdfKR2mY"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  recall_butler_data:
  recall_butler_test_data:
